### ISSUE TITLE
link2GI::linkGRASS7()

### ISSUE THREAD

**Issue by Nowosad** [r-spatial/link2GI#56]
Hi once more -- given the release of GRASS 8 and  recent renaming of rgrass7 to rgrass (https://cran.r-project.org/package=rgrass), what are your plans to `linkGRASS7()`? Do you plan to keep it, or maybe replace it (`linkGRASS()`), or maybe add a new function (`linkGRASS8()`)?

**Comment by gisma** [comment]
In the current development I would like to change the function to `linkGRASS( )` (with an alias on `linkGRASS7` to keep compatible). On the one hand this would consistent with `findGRASS()` and on the other hand the user usually doesn't care if he is working with GRASS 6x 7x 8x... I would then internally compare the versions and automatically link the most current one. Otherwise, the desired GRASS can be linked as before via an explicit call. 
Because of the let's say "grown" structure it will be more work than actually necessary, but I need for sure a few weeks. 
Therefore a simple adjustment on `GRASS` 8x. and `rgrass` with a call `linkGRASS8()` would be less elegant but clearly faster on CRAN.
Both options would be backwards compatible and those who use it would not have to fix their scripts.

**Comment by gisma** [comment]
@Nowosad is on the way to CRAN. 
Will be happy for all comments if not working

**Comment by Nowosad** [comment]
Perfect! I am at OpenGeoHub now, so I plan to take a look at the new version next week.

**Comment by Nowosad** [comment]
Ok -- I could not wait -- everything seem to be working fine -- see https://geocompr.robinlovelace.net/gis.html#grass.

**Comment by gisma** [comment]
Great thanks for the feedback!
 If you like I could provide a 2 liner for using the link2GI OTB wrapper which is pretty convenient to call the OTB functions directly from R without using QGIS

**Comment by Nowosad** [comment]
Yes!
