### ISSUE TITLE
Problem calling OTB using link2GI

### ISSUE THREAD

**Issue by Kalondepatrick** [r-spatial/link2GI#65]
I recently learned about Link2GI and have been attempting to use it to call OTB for image segmentation. However, I encountered a challenge: `Error: Cannot open 'intermediaries/sr_1rr_1.shp`; The file doesn't seem to exist." This issue suggests that the output file should be present before it was created, which sounds strange to me. I just want to inquire whether there is something that I am missing to successfully run OTB for segmentation using Link2GI. To reproduce my work, clone my repository here: https://github.com/Kalondepatrick/Link2GI_TestOTB , open the project file `link2GI.Rproj`, and execute the `segmentation` script located in the `scripts` folder. Thank you in advance for your assistance.

**Comment by gisma** [comment]
Hi @Kalondepatrick Basically I think the line
```
fn <- system.file("inputs/optical.tif", package = "terra")
````
leads to an empty filname (at least under my installation.
If you use :
```
fn <- system.file("ex/logo.tif", package = "terra")
````
It seems to run. In the cmd list the empty filename string  is not checked by link2GI . So it tries to return an not existing outpuput file. I will fix this asap. However if you retry please re-install the current github version.
cheers Chris

**Comment by Kalondepatrick** [comment]
Hello @gisma. Thank you very much for your assistance. From my understanding, it seems that the line `fn <- system.file("ex/logo.tif", package = "terra")` was simply intended to pass the raster file for segmentation.

I also attempted to directly read the file specified through `fn` within the function, but unfortunately, the problem persists. Upon closer examination of the issue, the traceback provided below indicates the same error:

`stop(structure(list(message = "Cannot open \"intermediaries/sr_1rr_1.shp\"; The file doesn't seem to exist.",
call = NULL, cppstack = NULL), class = c("Rcpp::exception",
"C++Error", "error", "condition")))`

`CPL_read_ogr(dsn, layer, query, as.character(options), quiet,
type, fid_column_name, drivers, wkt_filter, promote_to_multi,
int64_as_string, dsn_exists, dsn_isdb, getOption("width"))`

**Comment by gisma** [comment]
The problem is that I do not catch any errors in the command list. So if an invalid or non-existing argument is passed, the OTB algorithm is started and does not abort with the error message "Input file not available" but R tries to read in the output file (which was not created) (default is `retRaster=TRUE`) and does not find this file. 

Then there is an error in the call, namely that the list entry for the selected algorithm is not `$input` but `$input_in`.
The following excerpt should work:


```

library(link2GI)
library(terra)
library(listviewer)

# Connect to OTB
otblink <- link2GI::linkOTB()
projRootDir <- 'tmp'

# Check if output directory exists, if not, create it
if (!dir.exists(projRootDir)) {
  dir.create(projRootDir)
}


# Path to input file
fn <- system.file("ex/logo.tif", package = "terra")

# Algorithm keyword
algoKeyword <- "Segmentation"

spatRadius = 20
spatRange = 20
# Function to run OTB segmentation

  # Extract command list for the chosen algorithm 
cmd <- parseOTBFunction(algo = algoKeyword, gili = otblink)
  
  # Define mandatory arguments, with other arguments set to defaults
  cmd$help = NULL # drop the help entries
  cmd$input_in <- fn   # NOTE it is nNOT input but input_in
  cmd$filter <- "meanshift"
  cmd$filter.meanshift.spatialr <- spatRadius
  cmd$filter.meanshift.ranger <- spatRange
  cmd$mode.vector.outmode <- "ulco"
  cmd$mode.vector.out <- file.path(projRootDir, paste0("sr_", spatRadius, "rr_", spatRange, ".shp"))
  
  # Run algorithm
  retStack <- runOTB(cmd, gili = otblink)

plot (retStack)


```

**Comment by Kalondepatrick** [comment]
I got it, it's working now. Thank you so much.

**Comment by Kalondepatrick** [comment]
@gisma , I've observed that even after I modify the `fn` to specify my optical imagery as `fn <- system.file("inputs/optical.tif", package = "terra")`, it continues to use the R logo instead. In other words, it doesn't seem to recognize my data. Could you please review my updated code once more?

**Comment by gisma** [comment]
@Kalondepatrick 
If i call 

`fn <- system.file("inputs/optical.tif", package = "terra")` it is resulting in 
`""`
Please check if path and file exist and if you really pass this new argument to the list. Otherwise it will provide you the already existing shp file bexause as i already admitted there is no control if the command  list is setup correctly. So if you are using the same names etc. An not existing new input file will result in the already existing output of a former run...
